name: production

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/juanj9805/firmeza
          docker build -f Dockerfile -t $IMAGE:latest .
          docker push $IMAGE:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            IMAGE=ghcr.io/juanj9805/firmeza
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN }}
            docker pull $IMAGE:latest
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker run -d --name ${{ github.event.repository.name }} \
              --network firmeza-net \
              --restart always \
              -p 8080:8080 \
              -e ConnectionStrings__SqlConnection="${{ secrets.DB_CONNECTION_STRING }}" \
              $IMAGE:latest
